name: Test UV Cookiecutter

on:
  pull_request: {}
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.13', '3.14']
        os: [ubuntu-latest]

    name: Python ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - run: curl -sfL https://direnv.net/install.sh | bash

      - run: uv run ruff format .
      - run: uv run ruff check .
      - run: uv run ty check
      - run: uv run pytest --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


      - name: Configure git
        run: |
          git config --global user.email "default@example.com"
          git config --global user.name "Default Name"
          git config --global init.defaultBranch master

      - name: Run cookiecutter
        run: uvx cookiecutter . --no-input --config-file template_config.yml -o ..

      - name: Move to new package and run checks
        run: |
          cd ../uv_project
          direnv allow .
          uv run pre-commit run --all-files
